## Chapter_01:  Vectors, Matrices and Multidimensional Arrays

### Importing the modules:

In [1]:
import numpy as np

### The numpy array object:

In [2]:
help(np.ndarray)

s a "convenience" alternative to the tuple form)
 |      
 |      Returns
 |      -------
 |      out : ndarray
 |          View of `a`, with axes suitably permuted.
 |      
 |      See Also
 |      --------
 |      ndarray.T : Array property returning the array transposed.
 |      ndarray.reshape : Give a new shape to an array without changing its data.
 |      
 |      Examples
 |      --------
 |      >>> a = np.array([[1, 2], [3, 4]])
 |      >>> a
 |      array([[1, 2],
 |             [3, 4]])
 |      >>> a.transpose()
 |      array([[1, 3],
 |             [2, 4]])
 |      >>> a.transpose((1, 0))
 |      array([[1, 3],
 |             [2, 4]])
 |      >>> a.transpose(1, 0)
 |      array([[1, 3],
 |             [2, 4]])
 |  
 |  var(...)
 |      a.var(axis=None, dtype=None, out=None, ddof=0, keepdims=False)
 |      
 |      Returns the variance of the array elements, along given axis.
 |      
 |      Refer to `numpy.var` for full documentation.
 |      
 |      See Also
 |      --

In [3]:
# Example_1

data = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(f"type(data): {type(data)}\n")
print(f"data: \n{data}\n")
print(f"data.ndim: {data.ndim}\n")
print(f"data.shape: {data.shape}\n")
print(f"data.size: {data.size}\n")
print(f"data.dtype: {data.dtype}\n")
print(f"data.nbytes: {data.nbytes}\n")

type(data): <class 'numpy.ndarray'>

data: 
[[1 2]
 [3 4]
 [5 6]]

data.ndim: 2

data.shape: (3, 2)

data.size: 6

data.dtype: int64

data.nbytes: 48



### Data types:

In [4]:
# Example_2

print(f"int dtype: {np.array([1, 2, 3], dtype=np.int)}\n")
print(f"float dtype: {np.array([1, 2, 3], dtype=np.float)}\n")
print(f"complex dtype: {np.array([1, 2, 3], dtype=np.complex)}\n")

int dtype: [1 2 3]

float dtype: [1. 2. 3.]

complex dtype: [1.+0.j 2.+0.j 3.+0.j]



In [5]:
# Typecasting an array is straightforward and
# can be done using either the np.array function:
# Example_3:

data = np.array([1, 2, 3], dtype=np.float)
print(f"data: {data}")
print(f"data.dtype: {data.dtype}\n")

data = np.array(data, dtype=np.int)
print(f"data,dtype: {data.dtype}")
print(f"data: {data}")

data: [1. 2. 3.]
data.dtype: float64

data,dtype: int64
data: [1 2 3]


In [6]:
# or by using the astype method of the ndarray class:
# astype ---> Copy of the array, cast to a specified type.
# Example_4:

data = np.array([1, 2, 3], dtype=np.float)
print(f"data: {data}")

data = data.astype(np.int)
print(f"data: {data}")

data: [1. 2. 3.]
data: [1 2 3]


In [7]:
# When computing with NumPy arrays, the data type might get promoted from one
# type to another, if required by the operation
# Example_5

d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)

d3 = d1 + d2
print(f"d3: {d3}")
print(f"d3.dtype: {d3.dtype}")

d3: [2.+0.j 4.+0.j 6.+0.j]
d3.dtype: complex128


In [8]:
# In some cases, depending on the application and its requirements, it is essential to
# create arrays with data type appropriately set to
# Example_6

# this raises a warning
np.sqrt(np.array([-1, 0, 1]))

# this is correct
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### real and imaginary parts:

In [10]:
# Example_7

data = np.array([1, 2, 3], dtype=complex)
print(f"data: {data}\n")
print(f"data.real: {data.real}\n")
print(f"data.img: {data.imag}")

data: [1.+0.j 2.+0.j 3.+0.j]

data.real: [1. 2. 3.]

data.img: [0. 0. 0.]


### Creating Arrays:

### Arrays Created from Lists and Other Array-Like Objects:

In [9]:
# Example_8
# Creating 1-Dimensional Array
data = np.array([1, 2, 3, 4])
print(f"data: {data}\n")
print(f"data.ndim: {data.ndim}\n")
print(f"data.shape: {data.shape}")

data: [1 2 3 4]

data.ndim: 1

data.shape: (4,)


In [11]:
# Example_9
# Creating 2-Dimensional Array
data = np.array([
    [1, 2],
    [3, 4]
])
print(f"data: \n{data}\n")
print(f"data.ndim: {data.ndim}\n")
print(f"data.shape: {data.shape}")

data: 
[[1 2]
 [3 4]]

data.ndim: 2

data.shape: (2, 2)


### Arrays filled with constant values:

In [12]:
# Example_10
# np.zeros():

data = np.zeros((2, 3))
print(f"data: \n{data}")

data: 
[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Example_11
# np.ones():

data = np.ones(4)
print(f"data: {data}\n")
print(f"data.dtype: {data.dtype}\n")

data = np.ones(4, dtype=np.int)
print(f"data.dtype: {data.dtype}\n")

data: [1. 1. 1. 1.]

data.dtype: float64

data.dtype: int64



In [14]:
# Example_12
# np.full():

x1 = 5.4 * np.ones(10)
x2 = np.full(10, 5.4)

print(f"x1: {x1}\n")
print(f"x2: {x2}\n")

x1: [5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4]

x2: [5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4 5.4]



In [15]:
# Example_13

x1 = np.empty(5)
x1.fill(3.0)
print(f"x1: {x1}\n")

x2 = np.full(5, 3.0)
print(f"x2: {x2}")

x1: [3. 3. 3. 3. 3.]

x2: [3. 3. 3. 3. 3.]


### Arrays Filled with Incremental Sequences:

In [16]:
# Example_14

x1 = np.arange(0.0, 10, 1)
print(f"x1: {x1}\n")

x2 = np.linspace(0, 10, 11)
print(f"x2: {x2}\n")

x3 = np.linspace(0, 10, 10, endpoint=False)
print(f"x3: {x3}")

x1: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

x2: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

x3: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### Arrays Filled with Logarithmic Sequences:

In [17]:
# Example_15

x = np.logspace(0, 2, 5)    # # 5 data points between 10**0=1 to 10**2=100
print(f"x: {x}")

x: [  1.           3.16227766  10.          31.6227766  100.        ]


### Meshgrid Arrays:

In [18]:
# Example_16

x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

X, Y = np.meshgrid(x, y)

print(f"X: \n{X}\n")
print(f"Y: \n{Y}")

X: 
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]

Y: 
[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]


In [19]:
# Example_17

Z = (X + Y) ** 2
print(f"Z: \n{Z}")

Z: 
[[9 4 1]
 [1 0 1]
 [1 4 9]]


### Creating Uninitialized Arrays:

In [20]:
# Example_18

x = np.empty(3, dtype=np.float)
print(f"x: {x}")

x: [1. 2. 3.]


### Creating Arrays with Properties of Other Arrays:

In [21]:
# Example_19

def f(a):
    y = np.ones_like(a)
    return y


# testing
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

new = f(x)
print(f"new: \n{new}")

new: 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Creating Matrix Arrays:

In [22]:
# Example_20
# np.identity():

x = np.identity(4)
print(f"x: \n{x}")

x: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# Example_21
# np.eye()

x1 = np.eye(3)
print(f"x1: \n{x1}\n")

x2 = np.eye(3, k=1)
print(f"x2: \n{x2}\n")

x3 = np.eye(3, k=-1)
print(f"x3: \n{x3}")

x1: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

x2: 
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

x3: 
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


To construct a matrix with an arbitrary one-dimensional array on the diagonal, we
can use the np.diag function (which also takes the optional keyword argument k to
specify an offset from the diagonal)

In [24]:
# Example_22
x = np.diag(np.arange(0, 20, 5))
print(f"x: \n{x}")

x: 
[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


### Indexing and Slicing
#### One-Dimensional Arrays:

a[m] --> Select element at index m, where m is an integer (start counting form 0).

a[-m] --> Select the n th element from the end of the list, where n is an integer.

a[m:n] --> Select elements with index starting at m and ending at n − 1 (m and n are integers).

a[:] or a[0:-1] --> Select all elements in the given axis.

a[:n] --> Select elements starting with index 0 and going up to index n − 1 (integer).

a[m:] or a[m:-1] --> Select elements starting with index m (integer) and going up to the last element in the array.

a[m:n:p] --> Select elements with index m through n (exclusive), with increment p.

a[::-1] --> Select all the elements, in reverse order.

In [25]:
# Example_23

a = np.arange(0, 11)
print(f"a: {a}\n")

print(f"a[0] --> the first element --> {a[0]}\n")
print(f"a[-1] --> the last element --> {a[-1]}\n")
print(f"a[4] --> the fifth element, at index 4 --> {a[4]}\n")
print(f"a[1:-1] --> from the second to the second-to-last element --> {a[1:-1]}\n")
print(f"a[a1:-1:2] --> selecting every element and every second element --> {a[1:-1:2]}\n")
print(f"a[:5] --> select the first five elements --> {a[:5]}\n")
print(f"a[-5:] --> Select the last five elements --> {a[-5:]}\n")
print(f"a[::-2] --> Reverse the array and select only every second value --> {a[::-2]}")

a: [ 0  1  2  3  4  5  6  7  8  9 10]

a[0] --> the first element --> 0

a[-1] --> the last element --> 10

a[4] --> the fifth element, at index 4 --> 4

a[1:-1] --> from the second to the second-to-last element --> [1 2 3 4 5 6 7 8 9]

a[a1:-1:2] --> selecting every element and every second element --> [1 3 5 7 9]

a[:5] --> select the first five elements --> [0 1 2 3 4]

a[-5:] --> Select the last five elements --> [ 6  7  8  9 10]

a[::-2] --> Reverse the array and select only every second value --> [10  8  6  4  2  0]


#### Multidimensional Arrays:

In [26]:
# Example_24

f = lambda m, n: n + 10*m
A = np.fromfunction(f, (6,6), dtype=int)
print(f"A: \n{A}\n")

print(f"A[:, 1] --> Select the second column --> {A[:, 1]}")
print(f"A[1, :] --> Select the second row --> {A[1, :]}")

A: 
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

A[:, 1] --> Select the second column --> [ 1 11 21 31 41 51]
A[1, :] --> Select the second row --> [10 11 12 13 14 15]


By applying a slice on each of the array axes, we can extract subarrays (submatrices
in this two-dimensional example):

In [27]:
# Example_25

print(f"A[:3, :3] --> nupper half diagonal block matrix --> \n{A[:3, :3]}\n")
print(f"A[3:, :3] --> lower left off-diagonal block matrix --> \n{A[3:, :3]}\n")


A[:3, :3] --> nupper half diagonal block matrix --> 
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]

A[3:, :3] --> lower left off-diagonal block matrix --> 
[[30 31 32]
 [40 41 42]
 [50 51 52]]



With element spacing other that 1, submatrices made up from nonconsecutive
elements can be extracted:

In [28]:
# Example_26

print(f"A[::2, ::2] --> every second element starting from 0, 0 --> \n{A[::2, ::2]}\n")
print(f"A[1::2, 1::3] --> every second and third elementstarting from 1, 1 --> \n{A[1::2, 1::3]}")

A[::2, ::2] --> every second element starting from 0, 0 --> 
[[ 0  2  4]
 [20 22 24]
 [40 42 44]]

A[1::2, 1::3] --> every second and third elementstarting from 1, 1 --> 
[[11 14]
 [31 34]
 [51 54]]


### Views:
#### When elements in a view are assigned new values, the values of the original array are therefore also updated:

In [29]:
# Example_27

B = A[1:5, 1:5]
print(f"B: \n{B}\n")

B[:, :] = 0
print(f"A: \n{A}")


B: 
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]

A: 
[[ 0  1  2  3  4  5]
 [10  0  0  0  0 15]
 [20  0  0  0  0 25]
 [30  0  0  0  0 35]
 [40  0  0  0  0 45]
 [50 51 52 53 54 55]]


In [30]:
# Example_28

C = B[1:3, 1:3].copy()
print(f"C: \n{C}\n")

C[:, :] = 1     # this does not affect B
print(f"C: \n{C}\n")
print(f"B: \n{B}")


C: 
[[0 0]
 [0 0]]

C: 
[[1 1]
 [1 1]]

B: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### fancy Indexing and Boolean-Valued Indexing

In [31]:
# Example_29

A = np.linspace(0, 1, 11)
print(f"A: {A}\n")

print(f"A[0, 2, 4]: {A[np.array([0, 2, 4])]}\n")

# The same thing can be accomplished by indexing with a python list
print(f"A[[0, 2, 4]]: {A[[0, 2, 4]]}")

A: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

A[0, 2, 4]: [0.  0.2 0.4]

A[[0, 2, 4]]: [0.  0.2 0.4]


In [32]:
# Example_30

# select all the elements from the array A that exceed the value 0.5:
print(f"A > 0.5 : {A > 0.5}\n")
print(f"A[A > 0.5]: {A[A > 0.5]}")

A > 0.5 : [False False False False False False  True  True  True  True  True]

A[A > 0.5]: [0.6 0.7 0.8 0.9 1. ]


In [33]:
# Example_31

A = np.arange(10)
indices = [2, 4, 6]
B = A[indices]
B[0] = -1   # this does not affect A
print(f"A: {A}\n")
A[indices] = -1     # this alters A
print(f"A: {A}")


A: [0 1 2 3 4 5 6 7 8 9]

A: [ 0  1 -1  3 -1  5 -1  7  8  9]


In [34]:
# Example_32

A = np.arange(10)
B = A[A > 5]
B[0] = -1       # this does not affect A
print(f"A: {A}\n")

A[A > 5] = -1       # this alters A
print(f"A: {A}")


A: [0 1 2 3 4 5 6 7 8 9]

A: [ 0  1  2  3  4  5 -1 -1 -1 -1]


### Reshaping and Resizing:

In [35]:
# example_33

data = np.array([
    [1, 2],
    [3, 4]
])
print(f"data: \n{data}\n")

x = np.reshape(data, (1, 4))
print(f"x: {x}\n")

y = data.reshape(4)
print(f"y: {y}")

data: 
[[1 2]
 [3 4]]

x: [[1 2 3 4]]

y: [1 2 3 4]


In [36]:
# Example_34

data = np.array([
    [1, 2],
    [3, 4]
])
print(f"data: \n{data}\n")

x = data.flatten()
print(f"x: {x}\n")
print(f"data.flatten().shape: {data.flatten().shape}")

data: 
[[1 2]
 [3 4]]

x: [1 2 3 4]

data.flatten().shape: (4,)


In [37]:
# Example_35

data = np.arange(0, 5)
print(f"data: {data}\n")

column = data[:, np.newaxis]
print(f"column: \n{column}\n")

row = data[np.newaxis, :]
print(f"row: {row}")

data: [0 1 2 3 4]

column: 
[[0]
 [1]
 [2]
 [3]
 [4]]

row: [[0 1 2 3 4]]


In [38]:
# Example_36

data = np.arange(5)
print(f"data: {data}\n")

v_stack = np.vstack((data, data, data))
print(f"v_stack: \n{v_stack}\n")

data: [0 1 2 3 4]

v_stack: 
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]



In [39]:
# Example_37

data = np.arange(5)
print(f"data: {data}\n")

h_stack = np.hstack((data, data, data))
print(f"h_stack: {h_stack}")

data: [0 1 2 3 4]

h_stack: [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [40]:
# Example_38

data = data[:, np.newaxis]
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

### Vectorized Expressions:
#### ArithmeticOperations:

In [42]:
# Example_39

x = np.array([
    [1, 2],
    [3, 4]
])

y = np.array([
    [5, 6],
    [7, 8]
])

z = x + y
print(f"z: \n{z}\n")

z: 
[[ 6  8]
 [10 12]]



In [41]:
# Example_40

z = y - x
print(f"z: \n{z}")

z: 
[0 0 0 0]


In [43]:
# Example_41

z = x * y
print(f"z: \n{z}")

z: 
[[ 5 12]
 [21 32]]


In [44]:
# example_42

z = y / x
print(f"z: \n{z}")

z: 
[[5.         3.        ]
 [2.33333333 2.        ]]


In operations between scalars and arrays, the scalar value is applied to each element
in the array, as one could expect:

In [ ]:
# Example_43
res = x * 2
print(f"res : \n{res}")